server:
  port: 8079
spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_reservation
    username: springstudent
    password: springstudent
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  main:
    banner-mode: off
app:
  jwtSecret: S5arZ8qX8Anvk60LIHdGKZiGyLAyxW+LU1Xw2H4R6Uu1ndlUNPqhpVuKtFsfFvA+
  jwtCryptoSecret : sBnlg0BGosgPMQju
logging:
  level:
    org.springframework: DEBUG